[package]
name = "upfront"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
difference = "2.0"
clap = { version = "4.0", features = ["derive"] }

